[project]
name = "password-manager"
version = "0.1.0"
dependencies = [
    "bcrypt",
    "cryptography",
    "rich",
    "prompt-toolkit",
    "pyotp",
    "qrcode",
    "pyperclip",
    "wordfreq",
    "pytest-mock",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--strict-markers"
